version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: property_pg
    environment:
      POSTGRES_DB: propertiesdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: property_es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  property-api:
    build: .
    depends_on:
      - postgres
      - elasticsearch
    ports:
      - "5000:80"

volumes:
  pgdata:
  esdata:
